# Generated by Django 3.2.4 on 2021-06-26 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='anomalous', max_length=200)),
                ('bloodgroup', models.CharField(choices=[('A RhD positive (A+)', 'A+'), ('A RhD negative (A-)', 'A-'), ('B RhD positive (B+)', 'B+'), ('B RhD negative (B-)', 'B-'), ('O RhD positive (O+)', 'O+'), ('O RhD negative (O-)', 'O-'), ('AB RhD positive (AB+)', 'AB+'), ('AB RhD negative (AB-)', 'AB-')], max_length=200)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(18)])),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
    ]
